### ISSUE TITLE
please update and compile 

### ISSUE THREAD

**Issue by derbayer36** [Tankerch/COM3D2_DLC_Checker#14]
The source code has been updated like 2 moths ago. I hope you can compile it as *.exe
your work is much appreciated :D

**Comment by Kamikaze1903** [comment]
same problem as this guy, hope it gets updated to exe

**Comment by Tankerch** [comment]
Nothing is needed to update for the main program, and the DLC list will auto-update if you have an internet network.

**Comment by Kamikaze1903** [comment]
but its in .py, don't we have to convert it to exe ourselves before opening it?

**Comment by Tankerch** [comment]
@Kamikaze1903  
.EXE type ._.
https://github.com/Tankerch/COM3D2_DLC_Checker/releases
