### ISSUE TITLE
[COM3D2 Shop] [Giga - Ai Kiss Dance] DLC wrong file to check

### ISSUE THREAD

**Issue by derbayer36** [Tankerch/COM3D2_DLC_Checker#16]
[COM3D2 Shop] [Giga - Ai Kiss Dance] DLC does not contain the file "parts_dlc305.arc"

You should instead use one of these:

bg_dlc305.arc
csv_dlc305.arc
motion_dlc305.arc
script_dlc305.arc
sound_dlc305.arc
system_dlc305.arc
voice_dlc305.arc

**Comment by Tankerch** [comment]
Hi there,
I will check it soon, thank you for letting me know about this
