### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AstrNexus** [Tankerch/COM3D2_DLC_Checker#21]
Checking internet connection :
Connected
Traceback (most recent call last):
  File "D:\Dropbox\Transfer\Python\COM3D2 DLC Checker V2\COM_DLC_Checker.py", line 36, in <module>
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 4600: illegal multibyte sequence
[17540] Failed to execute script COM_DLC_Checker

Also, I don't have this folder.

**Comment by Tankerch** [comment]
LOL that's my dir folder in my PC for the source code of this project, that's weird. 

Yep, I got that error too. it's look like the new DLC list change the encoding to Windows CP950.

**Comment by Tankerch** [comment]
new .exe. is up. Maybe you can try that
https://github.com/Tankerch/COM3D2_DLC_Checker/releases/tag/1.0
